### ISSUE TITLE
We don't use hungarian notation when defining any constants or variables.

### ISSUE THREAD

**Issue by MeanEYE** [iliyaM/Oren-shtain-site#1]
This approach [here](https://github.com/iliyaM/Oren-shtain-site/blob/master/site/templates/home.xml#L42-L44) is completely wrong. Whole point of language constants is to allow them to be reused. Naming them with `_h2` and similar will confuse people and doesn't contribute anything.

Further more name is completely wrong. It doesn't describe language constant at all. Appropriate name would be `title_about` or something similar.

**Comment by iliyaM** [comment]
ok

**Comment by iliyaM** [comment]
what are hungarian notation?

**Comment by MeanEYE** [comment]
Hungarian notation is a bad practice from old days where you would describe
type of variable with variable name.

For example:
```JavaScript
var int_count = 5;
```

Completely useless as you already see number being stored and more to the
point name `count` already implies a number.

**Comment by iliyaM** [comment]
ok i can understant the about_h2 could be title_about
but what of the P?
what name should i come up with?

i have a lot of strings in the JSON file and i wanted to be as clear as i can be what is what.
on top of that! that the SUBLIME TEXT dosent show hebrew words so i have nothing to rely on when reading the file other that the var name i gave it.
so i used about(that's the name of the section) and h2 so ill understand that this is the big h2 in the about section
and after that i thought the most normal thing to is to call the other var a P.

**Comment by MeanEYE** [comment]
It's confusing when you name them like that and use them in different tags.
Describe the content not the container.
