### ISSUE TITLE
Stupid variable naming.

### ISSUE THREAD

**Issue by MeanEYE** [iliyaM/Oren-shtain-site#3]
[Grouping styles like these](https://github.com/iliyaM/Oren-shtain-site/blob/master/site/styles/main_mobile.less#L27-L30) in to a separate `common.less` file is much better as then you only import colors in both `main` files from a single one. Therefore changing the site revolves around changing one file instead of many other places.

Further more, naming something `color_blue` is stupid, because first of all value of color blue will never change and secondly if we ever change that to red or some other color you will have confusing name which will say _blue_ but is _red_ or you would have to go through all of the files and change `color_blue` to `color_red` at which point using variables is useless.

**Comment by iliyaM** [comment]
ok didnt thought of that from now on ill use common.less for the colors and import it as one file into main.

regarding the naming of the color
yo mean its better to use namings like @color_button or color_border somthing like that? 
and not actual color names?

**Comment by MeanEYE** [comment]
Exactly that. That way if you are redesigning the site changing colors of
buttons is easy. Instead of hunting where color blue was used.
